#!/bin/bash
set -e
# Install dependencies
if [ "$EUID" -ne 0 ]; then
    echo "Please run this script as root or using sudo."
    exit 1
fi

# Copy your Python script and files to the appropriate location
echo "copying the files to appropiate location..."
cp -r -p  vps/usr/bin/ /usr/local/bin/
echo "Copied Successfully..."

# Set permissions and ownership

echo "Setting Permissions..."
chmod +x /usr/local/bin/vps.py

echo "Done..."
echo "Successfully installed the package!!!"
